### ISSUE TITLE
conflict because extension "BitBake language support" is deprecated.

### ISSUE THREAD

**Issue by stevo01** [priv-kweihmann/oelint-vscode#10]
I am using the oelint-adv and the vscode plugin since end 2023 during reviews of different yocto recipes. The plugin stopped to work after an update of vs-code, to V1.88.1 . I assume the issue is caused from the vscode extension "BitBake language support" which is marked as deprecated in that version.

Can someone check it and give me recommendation how to fix it?

Best Regards

Steffen

**Comment by priv-kweihmann** [comment]
@stevo01 I just tested it with latest vscode 1.89 - works for me - but I have the recommended replacement extension https://marketplace.visualstudio.com/items?itemName=yocto-project.yocto-bitbake installed.
For this extension it is only important that some other extension provides a language support called 'bitbake'.

You could check if that is the case for you by opening any bb file in the editor, hit F1, search for `Change language mode`  and see if you still got 'Bitbake' as an option.
If not I would suggest to install that replacement extension, or alternatively define your own mapping for a 'bitbake' language.

Feel free to close the ticket if that helps, otherwise please provide more info, like
- installed extensions
- OS

**Comment by stevo01** [comment]
> You could check if that is the case for you by opening any bb file in the editor, hit F1, search for `Change language mode` and see if you still got 'Bitbake' as an option. If not I would suggest to install that replacement extension, or alternatively define your own mapping for a 'bitbake' language.

Thanks for the fast feedback. A short test of the "Yocto Projekt BitBake" extension shows, that a specific configuration is required for my setup because I am using yocto/thud inside a docker container. I plan a closer look into the extension next days.
